FROM golang:latest as builder
RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN go build -o main .
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./...

FROM alpine:latest AS production
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /build/ /app/
WORKDIR /app
CMD ["./main"]

#docker build -t hellocloudreachmain:1.1 . -f Dockerfile.multi
#... (build output omitted)
#docker images | grep hellocloudreachmain


